name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore ./McDoit.Aws.Lambda.Executors.slnx

      - name: Build
        run: dotnet build ./McDoit.Aws.Lambda.Executors.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test ./McDoit.Aws.Lambda.Executors.slnx --configuration Release --no-build --verbosity minimal
